// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: mcsports/friend/v1/data.proto

package friendv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Paginated     *bool                  `protobuf:"varint,2,opt,name=paginated,proto3,oneof" json:"paginated,omitempty"`
	Page          *uint32                `protobuf:"varint,3,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Amount        *uint32                `protobuf:"varint,4,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsRequest) Reset() {
	*x = ListFriendsRequest{}
	mi := &file_mcsports_friend_v1_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsRequest) ProtoMessage() {}

func (x *ListFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_friend_v1_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsRequest.ProtoReflect.Descriptor instead.
func (*ListFriendsRequest) Descriptor() ([]byte, []int) {
	return file_mcsports_friend_v1_data_proto_rawDescGZIP(), []int{0}
}

func (x *ListFriendsRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ListFriendsRequest) GetPaginated() bool {
	if x != nil && x.Paginated != nil {
		return *x.Paginated
	}
	return false
}

func (x *ListFriendsRequest) GetPage() uint32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListFriendsRequest) GetAmount() uint32 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

type ListFriendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         uint32                 `protobuf:"varint,1,opt,name=pages,proto3" json:"pages,omitempty"`
	Friend        []*PlayerData          `protobuf:"bytes,2,rep,name=friend,proto3" json:"friend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsResponse) Reset() {
	*x = ListFriendsResponse{}
	mi := &file_mcsports_friend_v1_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsResponse) ProtoMessage() {}

func (x *ListFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_friend_v1_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsResponse.ProtoReflect.Descriptor instead.
func (*ListFriendsResponse) Descriptor() ([]byte, []int) {
	return file_mcsports_friend_v1_data_proto_rawDescGZIP(), []int{1}
}

func (x *ListFriendsResponse) GetPages() uint32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *ListFriendsResponse) GetFriend() []*PlayerData {
	if x != nil {
		return x.Friend
	}
	return nil
}

type ListFriendInvitesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Paginated     *bool                  `protobuf:"varint,2,opt,name=paginated,proto3,oneof" json:"paginated,omitempty"`
	Page          *uint32                `protobuf:"varint,3,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Amount        *uint32                `protobuf:"varint,4,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendInvitesRequest) Reset() {
	*x = ListFriendInvitesRequest{}
	mi := &file_mcsports_friend_v1_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendInvitesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendInvitesRequest) ProtoMessage() {}

func (x *ListFriendInvitesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_friend_v1_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendInvitesRequest.ProtoReflect.Descriptor instead.
func (*ListFriendInvitesRequest) Descriptor() ([]byte, []int) {
	return file_mcsports_friend_v1_data_proto_rawDescGZIP(), []int{2}
}

func (x *ListFriendInvitesRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ListFriendInvitesRequest) GetPaginated() bool {
	if x != nil && x.Paginated != nil {
		return *x.Paginated
	}
	return false
}

func (x *ListFriendInvitesRequest) GetPage() uint32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListFriendInvitesRequest) GetAmount() uint32 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

type ListFriendInvitesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         uint32                 `protobuf:"varint,1,opt,name=pages,proto3" json:"pages,omitempty"`
	Friend        []*PlayerData          `protobuf:"bytes,2,rep,name=friend,proto3" json:"friend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendInvitesResponse) Reset() {
	*x = ListFriendInvitesResponse{}
	mi := &file_mcsports_friend_v1_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendInvitesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendInvitesResponse) ProtoMessage() {}

func (x *ListFriendInvitesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_friend_v1_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendInvitesResponse.ProtoReflect.Descriptor instead.
func (*ListFriendInvitesResponse) Descriptor() ([]byte, []int) {
	return file_mcsports_friend_v1_data_proto_rawDescGZIP(), []int{3}
}

func (x *ListFriendInvitesResponse) GetPages() uint32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *ListFriendInvitesResponse) GetFriend() []*PlayerData {
	if x != nil {
		return x.Friend
	}
	return nil
}

type CheckFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	FriendIds     []string               `protobuf:"bytes,2,rep,name=friend_ids,json=friendIds,proto3" json:"friend_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFriendsRequest) Reset() {
	*x = CheckFriendsRequest{}
	mi := &file_mcsports_friend_v1_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFriendsRequest) ProtoMessage() {}

func (x *CheckFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_friend_v1_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFriendsRequest.ProtoReflect.Descriptor instead.
func (*CheckFriendsRequest) Descriptor() ([]byte, []int) {
	return file_mcsports_friend_v1_data_proto_rawDescGZIP(), []int{4}
}

func (x *CheckFriendsRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CheckFriendsRequest) GetFriendIds() []string {
	if x != nil {
		return x.FriendIds
	}
	return nil
}

type CheckFriendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*FriendStatus        `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFriendsResponse) Reset() {
	*x = CheckFriendsResponse{}
	mi := &file_mcsports_friend_v1_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFriendsResponse) ProtoMessage() {}

func (x *CheckFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_friend_v1_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFriendsResponse.ProtoReflect.Descriptor instead.
func (*CheckFriendsResponse) Descriptor() ([]byte, []int) {
	return file_mcsports_friend_v1_data_proto_rawDescGZIP(), []int{5}
}

func (x *CheckFriendsResponse) GetStatuses() []*FriendStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type FriendStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	AreFriends    bool                   `protobuf:"varint,2,opt,name=are_friends,json=areFriends,proto3" json:"are_friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendStatus) Reset() {
	*x = FriendStatus{}
	mi := &file_mcsports_friend_v1_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendStatus) ProtoMessage() {}

func (x *FriendStatus) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_friend_v1_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendStatus.ProtoReflect.Descriptor instead.
func (*FriendStatus) Descriptor() ([]byte, []int) {
	return file_mcsports_friend_v1_data_proto_rawDescGZIP(), []int{6}
}

func (x *FriendStatus) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *FriendStatus) GetAreFriends() bool {
	if x != nil {
		return x.AreFriends
	}
	return false
}

var File_mcsports_friend_v1_data_proto protoreflect.FileDescriptor

const file_mcsports_friend_v1_data_proto_rawDesc = "" +
	"\n" +
	"\x1dmcsports/friend/v1/data.proto\x12\x12mcsports.friend.v1\x1a\x1emcsports/friend/v1/types.proto\"\xac\x01\n" +
	"\x12ListFriendsRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12!\n" +
	"\tpaginated\x18\x02 \x01(\bH\x00R\tpaginated\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\x03 \x01(\rH\x01R\x04page\x88\x01\x01\x12\x1b\n" +
	"\x06amount\x18\x04 \x01(\rH\x02R\x06amount\x88\x01\x01B\f\n" +
	"\n" +
	"_paginatedB\a\n" +
	"\x05_pageB\t\n" +
	"\a_amount\"c\n" +
	"\x13ListFriendsResponse\x12\x14\n" +
	"\x05pages\x18\x01 \x01(\rR\x05pages\x126\n" +
	"\x06friend\x18\x02 \x03(\v2\x1e.mcsports.friend.v1.PlayerDataR\x06friend\"\xb2\x01\n" +
	"\x18ListFriendInvitesRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12!\n" +
	"\tpaginated\x18\x02 \x01(\bH\x00R\tpaginated\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\x03 \x01(\rH\x01R\x04page\x88\x01\x01\x12\x1b\n" +
	"\x06amount\x18\x04 \x01(\rH\x02R\x06amount\x88\x01\x01B\f\n" +
	"\n" +
	"_paginatedB\a\n" +
	"\x05_pageB\t\n" +
	"\a_amount\"i\n" +
	"\x19ListFriendInvitesResponse\x12\x14\n" +
	"\x05pages\x18\x01 \x01(\rR\x05pages\x126\n" +
	"\x06friend\x18\x02 \x03(\v2\x1e.mcsports.friend.v1.PlayerDataR\x06friend\"Q\n" +
	"\x13CheckFriendsRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"friend_ids\x18\x02 \x03(\tR\tfriendIds\"T\n" +
	"\x14CheckFriendsResponse\x12<\n" +
	"\bstatuses\x18\x01 \x03(\v2 .mcsports.friend.v1.FriendStatusR\bstatuses\"L\n" +
	"\fFriendStatus\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vare_friends\x18\x02 \x01(\bR\n" +
	"areFriends2\xbb\x02\n" +
	"\n" +
	"FriendData\x12j\n" +
	"\vListInvites\x12,.mcsports.friend.v1.ListFriendInvitesRequest\x1a-.mcsports.friend.v1.ListFriendInvitesResponse\x12^\n" +
	"\vListFriends\x12&.mcsports.friend.v1.ListFriendsRequest\x1a'.mcsports.friend.v1.ListFriendsResponse\x12a\n" +
	"\fCheckFriends\x12'.mcsports.friend.v1.CheckFriendsRequest\x1a(.mcsports.friend.v1.CheckFriendsResponseB\xcb\x01\n" +
	"\x16com.mcsports.friend.v1B\tDataProtoP\x01Z<github.com/bufbuild/buf-tour/gen/mcsports/friend/v1;friendv1\xa2\x02\x03MFX\xaa\x02\x12Mcsports.Friend.V1\xca\x02\x12Mcsports\\Friend\\V1\xe2\x02\x1eMcsports\\Friend\\V1\\GPBMetadata\xea\x02\x14Mcsports::Friend::V1b\x06proto3"

var (
	file_mcsports_friend_v1_data_proto_rawDescOnce sync.Once
	file_mcsports_friend_v1_data_proto_rawDescData []byte
)

func file_mcsports_friend_v1_data_proto_rawDescGZIP() []byte {
	file_mcsports_friend_v1_data_proto_rawDescOnce.Do(func() {
		file_mcsports_friend_v1_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcsports_friend_v1_data_proto_rawDesc), len(file_mcsports_friend_v1_data_proto_rawDesc)))
	})
	return file_mcsports_friend_v1_data_proto_rawDescData
}

var file_mcsports_friend_v1_data_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_mcsports_friend_v1_data_proto_goTypes = []any{
	(*ListFriendsRequest)(nil),        // 0: mcsports.friend.v1.ListFriendsRequest
	(*ListFriendsResponse)(nil),       // 1: mcsports.friend.v1.ListFriendsResponse
	(*ListFriendInvitesRequest)(nil),  // 2: mcsports.friend.v1.ListFriendInvitesRequest
	(*ListFriendInvitesResponse)(nil), // 3: mcsports.friend.v1.ListFriendInvitesResponse
	(*CheckFriendsRequest)(nil),       // 4: mcsports.friend.v1.CheckFriendsRequest
	(*CheckFriendsResponse)(nil),      // 5: mcsports.friend.v1.CheckFriendsResponse
	(*FriendStatus)(nil),              // 6: mcsports.friend.v1.FriendStatus
	(*PlayerData)(nil),                // 7: mcsports.friend.v1.PlayerData
}
var file_mcsports_friend_v1_data_proto_depIdxs = []int32{
	7, // 0: mcsports.friend.v1.ListFriendsResponse.friend:type_name -> mcsports.friend.v1.PlayerData
	7, // 1: mcsports.friend.v1.ListFriendInvitesResponse.friend:type_name -> mcsports.friend.v1.PlayerData
	6, // 2: mcsports.friend.v1.CheckFriendsResponse.statuses:type_name -> mcsports.friend.v1.FriendStatus
	2, // 3: mcsports.friend.v1.FriendData.ListInvites:input_type -> mcsports.friend.v1.ListFriendInvitesRequest
	0, // 4: mcsports.friend.v1.FriendData.ListFriends:input_type -> mcsports.friend.v1.ListFriendsRequest
	4, // 5: mcsports.friend.v1.FriendData.CheckFriends:input_type -> mcsports.friend.v1.CheckFriendsRequest
	3, // 6: mcsports.friend.v1.FriendData.ListInvites:output_type -> mcsports.friend.v1.ListFriendInvitesResponse
	1, // 7: mcsports.friend.v1.FriendData.ListFriends:output_type -> mcsports.friend.v1.ListFriendsResponse
	5, // 8: mcsports.friend.v1.FriendData.CheckFriends:output_type -> mcsports.friend.v1.CheckFriendsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mcsports_friend_v1_data_proto_init() }
func file_mcsports_friend_v1_data_proto_init() {
	if File_mcsports_friend_v1_data_proto != nil {
		return
	}
	file_mcsports_friend_v1_types_proto_init()
	file_mcsports_friend_v1_data_proto_msgTypes[0].OneofWrappers = []any{}
	file_mcsports_friend_v1_data_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcsports_friend_v1_data_proto_rawDesc), len(file_mcsports_friend_v1_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcsports_friend_v1_data_proto_goTypes,
		DependencyIndexes: file_mcsports_friend_v1_data_proto_depIdxs,
		MessageInfos:      file_mcsports_friend_v1_data_proto_msgTypes,
	}.Build()
	File_mcsports_friend_v1_data_proto = out.File
	file_mcsports_friend_v1_data_proto_goTypes = nil
	file_mcsports_friend_v1_data_proto_depIdxs = nil
}
