// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: mcsports/friend/v1/event.proto

package friendv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FriendAcceptEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	FriendId      string                 `protobuf:"bytes,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendAcceptEvent) Reset() {
	*x = FriendAcceptEvent{}
	mi := &file_mcsports_friend_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendAcceptEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendAcceptEvent) ProtoMessage() {}

func (x *FriendAcceptEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_friend_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendAcceptEvent.ProtoReflect.Descriptor instead.
func (*FriendAcceptEvent) Descriptor() ([]byte, []int) {
	return file_mcsports_friend_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *FriendAcceptEvent) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *FriendAcceptEvent) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

type FriendChatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	FriendId      string                 `protobuf:"bytes,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Component     *AdventureComponent    `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendChatEvent) Reset() {
	*x = FriendChatEvent{}
	mi := &file_mcsports_friend_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendChatEvent) ProtoMessage() {}

func (x *FriendChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_friend_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendChatEvent.ProtoReflect.Descriptor instead.
func (*FriendChatEvent) Descriptor() ([]byte, []int) {
	return file_mcsports_friend_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *FriendChatEvent) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *FriendChatEvent) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

func (x *FriendChatEvent) GetComponent() *AdventureComponent {
	if x != nil {
		return x.Component
	}
	return nil
}

var File_mcsports_friend_v1_event_proto protoreflect.FileDescriptor

const file_mcsports_friend_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x1emcsports/friend/v1/event.proto\x12\x12mcsports.friend.v1\x1a\x1emcsports/friend/v1/types.proto\"M\n" +
	"\x11FriendAcceptEvent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\tR\bfriendId\"\x91\x01\n" +
	"\x0fFriendChatEvent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\tR\bfriendId\x12D\n" +
	"\tcomponent\x18\x03 \x01(\v2&.mcsports.friend.v1.AdventureComponentR\tcomponentB\xcc\x01\n" +
	"\x16com.mcsports.friend.v1B\n" +
	"EventProtoP\x01Z<github.com/bufbuild/buf-tour/gen/mcsports/friend/v1;friendv1\xa2\x02\x03MFX\xaa\x02\x12Mcsports.Friend.V1\xca\x02\x12Mcsports\\Friend\\V1\xe2\x02\x1eMcsports\\Friend\\V1\\GPBMetadata\xea\x02\x14Mcsports::Friend::V1b\x06proto3"

var (
	file_mcsports_friend_v1_event_proto_rawDescOnce sync.Once
	file_mcsports_friend_v1_event_proto_rawDescData []byte
)

func file_mcsports_friend_v1_event_proto_rawDescGZIP() []byte {
	file_mcsports_friend_v1_event_proto_rawDescOnce.Do(func() {
		file_mcsports_friend_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcsports_friend_v1_event_proto_rawDesc), len(file_mcsports_friend_v1_event_proto_rawDesc)))
	})
	return file_mcsports_friend_v1_event_proto_rawDescData
}

var file_mcsports_friend_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mcsports_friend_v1_event_proto_goTypes = []any{
	(*FriendAcceptEvent)(nil),  // 0: mcsports.friend.v1.FriendAcceptEvent
	(*FriendChatEvent)(nil),    // 1: mcsports.friend.v1.FriendChatEvent
	(*AdventureComponent)(nil), // 2: mcsports.friend.v1.AdventureComponent
}
var file_mcsports_friend_v1_event_proto_depIdxs = []int32{
	2, // 0: mcsports.friend.v1.FriendChatEvent.component:type_name -> mcsports.friend.v1.AdventureComponent
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mcsports_friend_v1_event_proto_init() }
func file_mcsports_friend_v1_event_proto_init() {
	if File_mcsports_friend_v1_event_proto != nil {
		return
	}
	file_mcsports_friend_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcsports_friend_v1_event_proto_rawDesc), len(file_mcsports_friend_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcsports_friend_v1_event_proto_goTypes,
		DependencyIndexes: file_mcsports_friend_v1_event_proto_depIdxs,
		MessageInfos:      file_mcsports_friend_v1_event_proto_msgTypes,
	}.Build()
	File_mcsports_friend_v1_event_proto = out.File
	file_mcsports_friend_v1_event_proto_goTypes = nil
	file_mcsports_friend_v1_event_proto_depIdxs = nil
}
