// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: mcsports/friend/v1/types.proto

package friendv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdventureComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdventureComponent) Reset() {
	*x = AdventureComponent{}
	mi := &file_mcsports_friend_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdventureComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdventureComponent) ProtoMessage() {}

func (x *AdventureComponent) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_friend_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdventureComponent.ProtoReflect.Descriptor instead.
func (*AdventureComponent) Descriptor() ([]byte, []int) {
	return file_mcsports_friend_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *AdventureComponent) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

var File_mcsports_friend_v1_types_proto protoreflect.FileDescriptor

const file_mcsports_friend_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x1emcsports/friend/v1/types.proto\x12\x12mcsports.friend.v1\"(\n" +
	"\x12AdventureComponent\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04jsonB\xcc\x01\n" +
	"\x16com.mcsports.friend.v1B\n" +
	"TypesProtoP\x01Z<github.com/bufbuild/buf-tour/gen/mcsports/friend/v1;friendv1\xa2\x02\x03MFX\xaa\x02\x12Mcsports.Friend.V1\xca\x02\x12Mcsports\\Friend\\V1\xe2\x02\x1eMcsports\\Friend\\V1\\GPBMetadata\xea\x02\x14Mcsports::Friend::V1b\x06proto3"

var (
	file_mcsports_friend_v1_types_proto_rawDescOnce sync.Once
	file_mcsports_friend_v1_types_proto_rawDescData []byte
)

func file_mcsports_friend_v1_types_proto_rawDescGZIP() []byte {
	file_mcsports_friend_v1_types_proto_rawDescOnce.Do(func() {
		file_mcsports_friend_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcsports_friend_v1_types_proto_rawDesc), len(file_mcsports_friend_v1_types_proto_rawDesc)))
	})
	return file_mcsports_friend_v1_types_proto_rawDescData
}

var file_mcsports_friend_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mcsports_friend_v1_types_proto_goTypes = []any{
	(*AdventureComponent)(nil), // 0: mcsports.friend.v1.AdventureComponent
}
var file_mcsports_friend_v1_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcsports_friend_v1_types_proto_init() }
func file_mcsports_friend_v1_types_proto_init() {
	if File_mcsports_friend_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcsports_friend_v1_types_proto_rawDesc), len(file_mcsports_friend_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcsports_friend_v1_types_proto_goTypes,
		DependencyIndexes: file_mcsports_friend_v1_types_proto_depIdxs,
		MessageInfos:      file_mcsports_friend_v1_types_proto_msgTypes,
	}.Build()
	File_mcsports_friend_v1_types_proto = out.File
	file_mcsports_friend_v1_types_proto_goTypes = nil
	file_mcsports_friend_v1_types_proto_depIdxs = nil
}
