// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: mcsports/queue/v1/event.proto

package queuev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueueUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Before        *Queue                 `protobuf:"bytes,1,opt,name=before,proto3" json:"before,omitempty"`
	After         *Queue                 `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueUpdateEvent) Reset() {
	*x = QueueUpdateEvent{}
	mi := &file_mcsports_queue_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueUpdateEvent) ProtoMessage() {}

func (x *QueueUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_queue_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueUpdateEvent.ProtoReflect.Descriptor instead.
func (*QueueUpdateEvent) Descriptor() ([]byte, []int) {
	return file_mcsports_queue_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *QueueUpdateEvent) GetBefore() *Queue {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *QueueUpdateEvent) GetAfter() *Queue {
	if x != nil {
		return x.After
	}
	return nil
}

type QueueResolveEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         *Queue                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueResolveEvent) Reset() {
	*x = QueueResolveEvent{}
	mi := &file_mcsports_queue_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueResolveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueResolveEvent) ProtoMessage() {}

func (x *QueueResolveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_queue_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueResolveEvent.ProtoReflect.Descriptor instead.
func (*QueueResolveEvent) Descriptor() ([]byte, []int) {
	return file_mcsports_queue_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *QueueResolveEvent) GetQueue() *Queue {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *QueueResolveEvent) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

var File_mcsports_queue_v1_event_proto protoreflect.FileDescriptor

const file_mcsports_queue_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x1dmcsports/queue/v1/event.proto\x12\x11mcsports.queue.v1\x1a\x1dmcsports/queue/v1/types.proto\"t\n" +
	"\x10QueueUpdateEvent\x120\n" +
	"\x06before\x18\x01 \x01(\v2\x18.mcsports.queue.v1.QueueR\x06before\x12.\n" +
	"\x05after\x18\x02 \x01(\v2\x18.mcsports.queue.v1.QueueR\x05after\"`\n" +
	"\x11QueueResolveEvent\x12.\n" +
	"\x05queue\x18\x01 \x01(\v2\x18.mcsports.queue.v1.QueueR\x05queue\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverIdB\xc5\x01\n" +
	"\x15com.mcsports.queue.v1B\n" +
	"EventProtoP\x01Z:github.com/bufbuild/buf-tour/gen/mcsports/queue/v1;queuev1\xa2\x02\x03MQX\xaa\x02\x11Mcsports.Queue.V1\xca\x02\x11Mcsports\\Queue\\V1\xe2\x02\x1dMcsports\\Queue\\V1\\GPBMetadata\xea\x02\x13Mcsports::Queue::V1b\x06proto3"

var (
	file_mcsports_queue_v1_event_proto_rawDescOnce sync.Once
	file_mcsports_queue_v1_event_proto_rawDescData []byte
)

func file_mcsports_queue_v1_event_proto_rawDescGZIP() []byte {
	file_mcsports_queue_v1_event_proto_rawDescOnce.Do(func() {
		file_mcsports_queue_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcsports_queue_v1_event_proto_rawDesc), len(file_mcsports_queue_v1_event_proto_rawDesc)))
	})
	return file_mcsports_queue_v1_event_proto_rawDescData
}

var file_mcsports_queue_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mcsports_queue_v1_event_proto_goTypes = []any{
	(*QueueUpdateEvent)(nil),  // 0: mcsports.queue.v1.QueueUpdateEvent
	(*QueueResolveEvent)(nil), // 1: mcsports.queue.v1.QueueResolveEvent
	(*Queue)(nil),             // 2: mcsports.queue.v1.Queue
}
var file_mcsports_queue_v1_event_proto_depIdxs = []int32{
	2, // 0: mcsports.queue.v1.QueueUpdateEvent.before:type_name -> mcsports.queue.v1.Queue
	2, // 1: mcsports.queue.v1.QueueUpdateEvent.after:type_name -> mcsports.queue.v1.Queue
	2, // 2: mcsports.queue.v1.QueueResolveEvent.queue:type_name -> mcsports.queue.v1.Queue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mcsports_queue_v1_event_proto_init() }
func file_mcsports_queue_v1_event_proto_init() {
	if File_mcsports_queue_v1_event_proto != nil {
		return
	}
	file_mcsports_queue_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcsports_queue_v1_event_proto_rawDesc), len(file_mcsports_queue_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcsports_queue_v1_event_proto_goTypes,
		DependencyIndexes: file_mcsports_queue_v1_event_proto_depIdxs,
		MessageInfos:      file_mcsports_queue_v1_event_proto_msgTypes,
	}.Build()
	File_mcsports_queue_v1_event_proto = out.File
	file_mcsports_queue_v1_event_proto_goTypes = nil
	file_mcsports_queue_v1_event_proto_depIdxs = nil
}
