// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: mcsports/party/v1/data.proto

package partyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PartyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyRequest) Reset() {
	*x = PartyRequest{}
	mi := &file_mcsports_party_v1_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyRequest) ProtoMessage() {}

func (x *PartyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyRequest.ProtoReflect.Descriptor instead.
func (*PartyRequest) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_data_proto_rawDescGZIP(), []int{0}
}

func (x *PartyRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type PartyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Party         *Party                 `protobuf:"bytes,1,opt,name=party,proto3" json:"party,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyResponse) Reset() {
	*x = PartyResponse{}
	mi := &file_mcsports_party_v1_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyResponse) ProtoMessage() {}

func (x *PartyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyResponse.ProtoReflect.Descriptor instead.
func (*PartyResponse) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_data_proto_rawDescGZIP(), []int{1}
}

func (x *PartyResponse) GetParty() *Party {
	if x != nil {
		return x.Party
	}
	return nil
}

var File_mcsports_party_v1_data_proto protoreflect.FileDescriptor

const file_mcsports_party_v1_data_proto_rawDesc = "" +
	"\n" +
	"\x1cmcsports/party/v1/data.proto\x12\x11mcsports.party.v1\x1a\x1dmcsports/party/v1/types.proto\"+\n" +
	"\fPartyRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\"?\n" +
	"\rPartyResponse\x12.\n" +
	"\x05party\x18\x01 \x01(\v2\x18.mcsports.party.v1.PartyR\x05party2Z\n" +
	"\tPartyData\x12M\n" +
	"\bGetParty\x12\x1f.mcsports.party.v1.PartyRequest\x1a .mcsports.party.v1.PartyResponseB\xc4\x01\n" +
	"\x15com.mcsports.party.v1B\tDataProtoP\x01Z:github.com/bufbuild/buf-tour/gen/mcsports/party/v1;partyv1\xa2\x02\x03MPX\xaa\x02\x11Mcsports.Party.V1\xca\x02\x11Mcsports\\Party\\V1\xe2\x02\x1dMcsports\\Party\\V1\\GPBMetadata\xea\x02\x13Mcsports::Party::V1b\x06proto3"

var (
	file_mcsports_party_v1_data_proto_rawDescOnce sync.Once
	file_mcsports_party_v1_data_proto_rawDescData []byte
)

func file_mcsports_party_v1_data_proto_rawDescGZIP() []byte {
	file_mcsports_party_v1_data_proto_rawDescOnce.Do(func() {
		file_mcsports_party_v1_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcsports_party_v1_data_proto_rawDesc), len(file_mcsports_party_v1_data_proto_rawDesc)))
	})
	return file_mcsports_party_v1_data_proto_rawDescData
}

var file_mcsports_party_v1_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mcsports_party_v1_data_proto_goTypes = []any{
	(*PartyRequest)(nil),  // 0: mcsports.party.v1.PartyRequest
	(*PartyResponse)(nil), // 1: mcsports.party.v1.PartyResponse
	(*Party)(nil),         // 2: mcsports.party.v1.Party
}
var file_mcsports_party_v1_data_proto_depIdxs = []int32{
	2, // 0: mcsports.party.v1.PartyResponse.party:type_name -> mcsports.party.v1.Party
	0, // 1: mcsports.party.v1.PartyData.GetParty:input_type -> mcsports.party.v1.PartyRequest
	1, // 2: mcsports.party.v1.PartyData.GetParty:output_type -> mcsports.party.v1.PartyResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mcsports_party_v1_data_proto_init() }
func file_mcsports_party_v1_data_proto_init() {
	if File_mcsports_party_v1_data_proto != nil {
		return
	}
	file_mcsports_party_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcsports_party_v1_data_proto_rawDesc), len(file_mcsports_party_v1_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcsports_party_v1_data_proto_goTypes,
		DependencyIndexes: file_mcsports_party_v1_data_proto_depIdxs,
		MessageInfos:      file_mcsports_party_v1_data_proto_msgTypes,
	}.Build()
	File_mcsports_party_v1_data_proto = out.File
	file_mcsports_party_v1_data_proto_goTypes = nil
	file_mcsports_party_v1_data_proto_depIdxs = nil
}
