// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: mcsports/party/v1/interaction.proto

package partyv1

import (
	v1 "github.com/bufbuild/buf-tour/gen/mcsports/friend/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePartyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     string                 `protobuf:"bytes,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Settings      *PartySettings         `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	InvitedIds    []string               `protobuf:"bytes,3,rep,name=invited_ids,json=invitedIds,proto3" json:"invited_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePartyRequest) Reset() {
	*x = CreatePartyRequest{}
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePartyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartyRequest) ProtoMessage() {}

func (x *CreatePartyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartyRequest.ProtoReflect.Descriptor instead.
func (*CreatePartyRequest) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_interaction_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePartyRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *CreatePartyRequest) GetSettings() *PartySettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *CreatePartyRequest) GetInvitedIds() []string {
	if x != nil {
		return x.InvitedIds
	}
	return nil
}

type CreatePartyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedParty  *Party                 `protobuf:"bytes,1,opt,name=created_party,json=createdParty,proto3" json:"created_party,omitempty"`
	OfflineIds    []string               `protobuf:"bytes,2,rep,name=offline_ids,json=offlineIds,proto3" json:"offline_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePartyResponse) Reset() {
	*x = CreatePartyResponse{}
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePartyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartyResponse) ProtoMessage() {}

func (x *CreatePartyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartyResponse.ProtoReflect.Descriptor instead.
func (*CreatePartyResponse) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_interaction_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePartyResponse) GetCreatedParty() *Party {
	if x != nil {
		return x.CreatedParty
	}
	return nil
}

func (x *CreatePartyResponse) GetOfflineIds() []string {
	if x != nil {
		return x.OfflineIds
	}
	return nil
}

type DeletePartyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutorId    string                 `protobuf:"bytes,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePartyRequest) Reset() {
	*x = DeletePartyRequest{}
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePartyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePartyRequest) ProtoMessage() {}

func (x *DeletePartyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePartyRequest.ProtoReflect.Descriptor instead.
func (*DeletePartyRequest) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_interaction_proto_rawDescGZIP(), []int{2}
}

func (x *DeletePartyRequest) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

type DeletePartyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePartyResponse) Reset() {
	*x = DeletePartyResponse{}
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePartyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePartyResponse) ProtoMessage() {}

func (x *DeletePartyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePartyResponse.ProtoReflect.Descriptor instead.
func (*DeletePartyResponse) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_interaction_proto_rawDescGZIP(), []int{3}
}

type InvitePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutorId    string                 `protobuf:"bytes,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvitePlayerRequest) Reset() {
	*x = InvitePlayerRequest{}
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvitePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvitePlayerRequest) ProtoMessage() {}

func (x *InvitePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvitePlayerRequest.ProtoReflect.Descriptor instead.
func (*InvitePlayerRequest) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_interaction_proto_rawDescGZIP(), []int{4}
}

func (x *InvitePlayerRequest) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *InvitePlayerRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type InvitePlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvitePlayerResponse) Reset() {
	*x = InvitePlayerResponse{}
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvitePlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvitePlayerResponse) ProtoMessage() {}

func (x *InvitePlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvitePlayerResponse.ProtoReflect.Descriptor instead.
func (*InvitePlayerResponse) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_interaction_proto_rawDescGZIP(), []int{5}
}

type HandleInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleInviteRequest) Reset() {
	*x = HandleInviteRequest{}
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleInviteRequest) ProtoMessage() {}

func (x *HandleInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleInviteRequest.ProtoReflect.Descriptor instead.
func (*HandleInviteRequest) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_interaction_proto_rawDescGZIP(), []int{6}
}

func (x *HandleInviteRequest) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *HandleInviteRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *HandleInviteRequest) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type HandleInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleInviteResponse) Reset() {
	*x = HandleInviteResponse{}
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleInviteResponse) ProtoMessage() {}

func (x *HandleInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleInviteResponse.ProtoReflect.Descriptor instead.
func (*HandleInviteResponse) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_interaction_proto_rawDescGZIP(), []int{7}
}

type LeavePartyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeavePartyRequest) Reset() {
	*x = LeavePartyRequest{}
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeavePartyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeavePartyRequest) ProtoMessage() {}

func (x *LeavePartyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeavePartyRequest.ProtoReflect.Descriptor instead.
func (*LeavePartyRequest) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_interaction_proto_rawDescGZIP(), []int{8}
}

func (x *LeavePartyRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type LeavePartyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeavePartyResponse) Reset() {
	*x = LeavePartyResponse{}
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeavePartyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeavePartyResponse) ProtoMessage() {}

func (x *LeavePartyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeavePartyResponse.ProtoReflect.Descriptor instead.
func (*LeavePartyResponse) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_interaction_proto_rawDescGZIP(), []int{9}
}

type PromoteMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	ExecutorId    string                 `protobuf:"bytes,2,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteMemberRequest) Reset() {
	*x = PromoteMemberRequest{}
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteMemberRequest) ProtoMessage() {}

func (x *PromoteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteMemberRequest.ProtoReflect.Descriptor instead.
func (*PromoteMemberRequest) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_interaction_proto_rawDescGZIP(), []int{10}
}

func (x *PromoteMemberRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *PromoteMemberRequest) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

type PromoteMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteMemberResponse) Reset() {
	*x = PromoteMemberResponse{}
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteMemberResponse) ProtoMessage() {}

func (x *PromoteMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteMemberResponse.ProtoReflect.Descriptor instead.
func (*PromoteMemberResponse) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_interaction_proto_rawDescGZIP(), []int{11}
}

type DemoteMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	ExecutorId    string                 `protobuf:"bytes,2,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemoteMemberRequest) Reset() {
	*x = DemoteMemberRequest{}
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoteMemberRequest) ProtoMessage() {}

func (x *DemoteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoteMemberRequest.ProtoReflect.Descriptor instead.
func (*DemoteMemberRequest) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_interaction_proto_rawDescGZIP(), []int{12}
}

func (x *DemoteMemberRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *DemoteMemberRequest) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

type DemoteMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemoteMemberResponse) Reset() {
	*x = DemoteMemberResponse{}
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoteMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoteMemberResponse) ProtoMessage() {}

func (x *DemoteMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoteMemberResponse.ProtoReflect.Descriptor instead.
func (*DemoteMemberResponse) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_interaction_proto_rawDescGZIP(), []int{13}
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Message       *v1.AdventureComponent `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_interaction_proto_rawDescGZIP(), []int{14}
}

func (x *ChatRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *ChatRequest) GetMessage() *v1.AdventureComponent {
	if x != nil {
		return x.Message
	}
	return nil
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_interaction_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_interaction_proto_rawDescGZIP(), []int{15}
}

var File_mcsports_party_v1_interaction_proto protoreflect.FileDescriptor

const file_mcsports_party_v1_interaction_proto_rawDesc = "" +
	"\n" +
	"#mcsports/party/v1/interaction.proto\x12\x11mcsports.party.v1\x1a\x1dmcsports/party/v1/types.proto\x1a\x1emcsports/friend/v1/types.proto\"\x92\x01\n" +
	"\x12CreatePartyRequest\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\tR\tcreatorId\x12<\n" +
	"\bsettings\x18\x02 \x01(\v2 .mcsports.party.v1.PartySettingsR\bsettings\x12\x1f\n" +
	"\vinvited_ids\x18\x03 \x03(\tR\n" +
	"invitedIds\"u\n" +
	"\x13CreatePartyResponse\x12=\n" +
	"\rcreated_party\x18\x01 \x01(\v2\x18.mcsports.party.v1.PartyR\fcreatedParty\x12\x1f\n" +
	"\voffline_ids\x18\x02 \x03(\tR\n" +
	"offlineIds\"5\n" +
	"\x12DeletePartyRequest\x12\x1f\n" +
	"\vexecutor_id\x18\x01 \x01(\tR\n" +
	"executorId\"\x15\n" +
	"\x13DeletePartyResponse\"S\n" +
	"\x13InvitePlayerRequest\x12\x1f\n" +
	"\vexecutor_id\x18\x01 \x01(\tR\n" +
	"executorId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\"\x16\n" +
	"\x14InvitePlayerResponse\"i\n" +
	"\x13HandleInviteRequest\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\"\x16\n" +
	"\x14HandleInviteResponse\"0\n" +
	"\x11LeavePartyRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\"\x14\n" +
	"\x12LeavePartyResponse\"T\n" +
	"\x14PromoteMemberRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12\x1f\n" +
	"\vexecutor_id\x18\x02 \x01(\tR\n" +
	"executorId\"\x17\n" +
	"\x15PromoteMemberResponse\"S\n" +
	"\x13DemoteMemberRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12\x1f\n" +
	"\vexecutor_id\x18\x02 \x01(\tR\n" +
	"executorId\"\x16\n" +
	"\x14DemoteMemberResponse\"l\n" +
	"\vChatRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12@\n" +
	"\amessage\x18\x02 \x01(\v2&.mcsports.friend.v1.AdventureComponentR\amessage\"\x0e\n" +
	"\fChatResponse2\xf9\x05\n" +
	"\x10PartyInteraction\x12\\\n" +
	"\vCreateParty\x12%.mcsports.party.v1.CreatePartyRequest\x1a&.mcsports.party.v1.CreatePartyResponse\x12\\\n" +
	"\vDeleteParty\x12%.mcsports.party.v1.DeletePartyRequest\x1a&.mcsports.party.v1.DeletePartyResponse\x12_\n" +
	"\fInvitePlayer\x12&.mcsports.party.v1.InvitePlayerRequest\x1a'.mcsports.party.v1.InvitePlayerResponse\x12_\n" +
	"\fHandleInvite\x12&.mcsports.party.v1.HandleInviteRequest\x1a'.mcsports.party.v1.HandleInviteResponse\x12Y\n" +
	"\n" +
	"LeaveParty\x12$.mcsports.party.v1.LeavePartyRequest\x1a%.mcsports.party.v1.LeavePartyResponse\x12b\n" +
	"\rPromoteMember\x12'.mcsports.party.v1.PromoteMemberRequest\x1a(.mcsports.party.v1.PromoteMemberResponse\x12_\n" +
	"\fDemoteMember\x12&.mcsports.party.v1.DemoteMemberRequest\x1a'.mcsports.party.v1.DemoteMemberResponse\x12G\n" +
	"\x04Chat\x12\x1e.mcsports.party.v1.ChatRequest\x1a\x1f.mcsports.party.v1.ChatResponseB\xcb\x01\n" +
	"\x15com.mcsports.party.v1B\x10InteractionProtoP\x01Z:github.com/bufbuild/buf-tour/gen/mcsports/party/v1;partyv1\xa2\x02\x03MPX\xaa\x02\x11Mcsports.Party.V1\xca\x02\x11Mcsports\\Party\\V1\xe2\x02\x1dMcsports\\Party\\V1\\GPBMetadata\xea\x02\x13Mcsports::Party::V1b\x06proto3"

var (
	file_mcsports_party_v1_interaction_proto_rawDescOnce sync.Once
	file_mcsports_party_v1_interaction_proto_rawDescData []byte
)

func file_mcsports_party_v1_interaction_proto_rawDescGZIP() []byte {
	file_mcsports_party_v1_interaction_proto_rawDescOnce.Do(func() {
		file_mcsports_party_v1_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcsports_party_v1_interaction_proto_rawDesc), len(file_mcsports_party_v1_interaction_proto_rawDesc)))
	})
	return file_mcsports_party_v1_interaction_proto_rawDescData
}

var file_mcsports_party_v1_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_mcsports_party_v1_interaction_proto_goTypes = []any{
	(*CreatePartyRequest)(nil),    // 0: mcsports.party.v1.CreatePartyRequest
	(*CreatePartyResponse)(nil),   // 1: mcsports.party.v1.CreatePartyResponse
	(*DeletePartyRequest)(nil),    // 2: mcsports.party.v1.DeletePartyRequest
	(*DeletePartyResponse)(nil),   // 3: mcsports.party.v1.DeletePartyResponse
	(*InvitePlayerRequest)(nil),   // 4: mcsports.party.v1.InvitePlayerRequest
	(*InvitePlayerResponse)(nil),  // 5: mcsports.party.v1.InvitePlayerResponse
	(*HandleInviteRequest)(nil),   // 6: mcsports.party.v1.HandleInviteRequest
	(*HandleInviteResponse)(nil),  // 7: mcsports.party.v1.HandleInviteResponse
	(*LeavePartyRequest)(nil),     // 8: mcsports.party.v1.LeavePartyRequest
	(*LeavePartyResponse)(nil),    // 9: mcsports.party.v1.LeavePartyResponse
	(*PromoteMemberRequest)(nil),  // 10: mcsports.party.v1.PromoteMemberRequest
	(*PromoteMemberResponse)(nil), // 11: mcsports.party.v1.PromoteMemberResponse
	(*DemoteMemberRequest)(nil),   // 12: mcsports.party.v1.DemoteMemberRequest
	(*DemoteMemberResponse)(nil),  // 13: mcsports.party.v1.DemoteMemberResponse
	(*ChatRequest)(nil),           // 14: mcsports.party.v1.ChatRequest
	(*ChatResponse)(nil),          // 15: mcsports.party.v1.ChatResponse
	(*PartySettings)(nil),         // 16: mcsports.party.v1.PartySettings
	(*Party)(nil),                 // 17: mcsports.party.v1.Party
	(*v1.AdventureComponent)(nil), // 18: mcsports.friend.v1.AdventureComponent
}
var file_mcsports_party_v1_interaction_proto_depIdxs = []int32{
	16, // 0: mcsports.party.v1.CreatePartyRequest.settings:type_name -> mcsports.party.v1.PartySettings
	17, // 1: mcsports.party.v1.CreatePartyResponse.created_party:type_name -> mcsports.party.v1.Party
	18, // 2: mcsports.party.v1.ChatRequest.message:type_name -> mcsports.friend.v1.AdventureComponent
	0,  // 3: mcsports.party.v1.PartyInteraction.CreateParty:input_type -> mcsports.party.v1.CreatePartyRequest
	2,  // 4: mcsports.party.v1.PartyInteraction.DeleteParty:input_type -> mcsports.party.v1.DeletePartyRequest
	4,  // 5: mcsports.party.v1.PartyInteraction.InvitePlayer:input_type -> mcsports.party.v1.InvitePlayerRequest
	6,  // 6: mcsports.party.v1.PartyInteraction.HandleInvite:input_type -> mcsports.party.v1.HandleInviteRequest
	8,  // 7: mcsports.party.v1.PartyInteraction.LeaveParty:input_type -> mcsports.party.v1.LeavePartyRequest
	10, // 8: mcsports.party.v1.PartyInteraction.PromoteMember:input_type -> mcsports.party.v1.PromoteMemberRequest
	12, // 9: mcsports.party.v1.PartyInteraction.DemoteMember:input_type -> mcsports.party.v1.DemoteMemberRequest
	14, // 10: mcsports.party.v1.PartyInteraction.Chat:input_type -> mcsports.party.v1.ChatRequest
	1,  // 11: mcsports.party.v1.PartyInteraction.CreateParty:output_type -> mcsports.party.v1.CreatePartyResponse
	3,  // 12: mcsports.party.v1.PartyInteraction.DeleteParty:output_type -> mcsports.party.v1.DeletePartyResponse
	5,  // 13: mcsports.party.v1.PartyInteraction.InvitePlayer:output_type -> mcsports.party.v1.InvitePlayerResponse
	7,  // 14: mcsports.party.v1.PartyInteraction.HandleInvite:output_type -> mcsports.party.v1.HandleInviteResponse
	9,  // 15: mcsports.party.v1.PartyInteraction.LeaveParty:output_type -> mcsports.party.v1.LeavePartyResponse
	11, // 16: mcsports.party.v1.PartyInteraction.PromoteMember:output_type -> mcsports.party.v1.PromoteMemberResponse
	13, // 17: mcsports.party.v1.PartyInteraction.DemoteMember:output_type -> mcsports.party.v1.DemoteMemberResponse
	15, // 18: mcsports.party.v1.PartyInteraction.Chat:output_type -> mcsports.party.v1.ChatResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_mcsports_party_v1_interaction_proto_init() }
func file_mcsports_party_v1_interaction_proto_init() {
	if File_mcsports_party_v1_interaction_proto != nil {
		return
	}
	file_mcsports_party_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcsports_party_v1_interaction_proto_rawDesc), len(file_mcsports_party_v1_interaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcsports_party_v1_interaction_proto_goTypes,
		DependencyIndexes: file_mcsports_party_v1_interaction_proto_depIdxs,
		MessageInfos:      file_mcsports_party_v1_interaction_proto_msgTypes,
	}.Build()
	File_mcsports_party_v1_interaction_proto = out.File
	file_mcsports_party_v1_interaction_proto_goTypes = nil
	file_mcsports_party_v1_interaction_proto_depIdxs = nil
}
