// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: mcsports/party/v1/types.proto

package partyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PartyRole int32

const (
	PartyRole_MEMBER PartyRole = 0
	PartyRole_MOD    PartyRole = 1
	PartyRole_OWNER  PartyRole = 2
)

// Enum value maps for PartyRole.
var (
	PartyRole_name = map[int32]string{
		0: "MEMBER",
		1: "MOD",
		2: "OWNER",
	}
	PartyRole_value = map[string]int32{
		"MEMBER": 0,
		"MOD":    1,
		"OWNER":  2,
	}
)

func (x PartyRole) Enum() *PartyRole {
	p := new(PartyRole)
	*p = x
	return p
}

func (x PartyRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PartyRole) Descriptor() protoreflect.EnumDescriptor {
	return file_mcsports_party_v1_types_proto_enumTypes[0].Descriptor()
}

func (PartyRole) Type() protoreflect.EnumType {
	return &file_mcsports_party_v1_types_proto_enumTypes[0]
}

func (x PartyRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PartyRole.Descriptor instead.
func (PartyRole) EnumDescriptor() ([]byte, []int) {
	return file_mcsports_party_v1_types_proto_rawDescGZIP(), []int{0}
}

type Party struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Settings      *PartySettings         `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	Members       []*PartyMember         `protobuf:"bytes,4,rep,name=members,proto3" json:"members,omitempty"`
	Invites       []*PartyInvite         `protobuf:"bytes,5,rep,name=invites,proto3" json:"invites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Party) Reset() {
	*x = Party{}
	mi := &file_mcsports_party_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Party) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Party) ProtoMessage() {}

func (x *Party) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Party.ProtoReflect.Descriptor instead.
func (*Party) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Party) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Party) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Party) GetSettings() *PartySettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Party) GetMembers() []*PartyMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Party) GetInvites() []*PartyInvite {
	if x != nil {
		return x.Invites
	}
	return nil
}

type PartyMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Role          PartyRole              `protobuf:"varint,2,opt,name=role,proto3,enum=mcsports.party.v1.PartyRole" json:"role,omitempty"`
	TimeJoined    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time_joined,json=timeJoined,proto3" json:"time_joined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyMember) Reset() {
	*x = PartyMember{}
	mi := &file_mcsports_party_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyMember) ProtoMessage() {}

func (x *PartyMember) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyMember.ProtoReflect.Descriptor instead.
func (*PartyMember) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *PartyMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PartyMember) GetRole() PartyRole {
	if x != nil {
		return x.Role
	}
	return PartyRole_MEMBER
}

func (x *PartyMember) GetTimeJoined() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeJoined
	}
	return nil
}

type PartyInvite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvitedName   string                 `protobuf:"bytes,1,opt,name=invited_name,json=invitedName,proto3" json:"invited_name,omitempty"`
	InvitorName   string                 `protobuf:"bytes,2,opt,name=invitor_name,json=invitorName,proto3" json:"invitor_name,omitempty"`
	TimeCreated   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time_created,json=timeCreated,proto3" json:"time_created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyInvite) Reset() {
	*x = PartyInvite{}
	mi := &file_mcsports_party_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyInvite) ProtoMessage() {}

func (x *PartyInvite) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyInvite.ProtoReflect.Descriptor instead.
func (*PartyInvite) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *PartyInvite) GetInvitedName() string {
	if x != nil {
		return x.InvitedName
	}
	return ""
}

func (x *PartyInvite) GetInvitorName() string {
	if x != nil {
		return x.InvitorName
	}
	return ""
}

func (x *PartyInvite) GetTimeCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeCreated
	}
	return nil
}

type PartySettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllowInvites  bool                   `protobuf:"varint,1,opt,name=allowInvites,proto3" json:"allowInvites,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,2,opt,name=isPrivate,proto3" json:"isPrivate,omitempty"`
	AllowChatting bool                   `protobuf:"varint,3,opt,name=allowChatting,proto3" json:"allowChatting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartySettings) Reset() {
	*x = PartySettings{}
	mi := &file_mcsports_party_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartySettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartySettings) ProtoMessage() {}

func (x *PartySettings) ProtoReflect() protoreflect.Message {
	mi := &file_mcsports_party_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartySettings.ProtoReflect.Descriptor instead.
func (*PartySettings) Descriptor() ([]byte, []int) {
	return file_mcsports_party_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *PartySettings) GetAllowInvites() bool {
	if x != nil {
		return x.AllowInvites
	}
	return false
}

func (x *PartySettings) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *PartySettings) GetAllowChatting() bool {
	if x != nil {
		return x.AllowChatting
	}
	return false
}

var File_mcsports_party_v1_types_proto protoreflect.FileDescriptor

const file_mcsports_party_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x1dmcsports/party/v1/types.proto\x12\x11mcsports.party.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe4\x01\n" +
	"\x05Party\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12<\n" +
	"\bsettings\x18\x03 \x01(\v2 .mcsports.party.v1.PartySettingsR\bsettings\x128\n" +
	"\amembers\x18\x04 \x03(\v2\x1e.mcsports.party.v1.PartyMemberR\amembers\x128\n" +
	"\ainvites\x18\x05 \x03(\v2\x1e.mcsports.party.v1.PartyInviteR\ainvites\"\x90\x01\n" +
	"\vPartyMember\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x04role\x18\x02 \x01(\x0e2\x1c.mcsports.party.v1.PartyRoleR\x04role\x12;\n" +
	"\vtime_joined\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"timeJoined\"\x92\x01\n" +
	"\vPartyInvite\x12!\n" +
	"\finvited_name\x18\x01 \x01(\tR\vinvitedName\x12!\n" +
	"\finvitor_name\x18\x02 \x01(\tR\vinvitorName\x12=\n" +
	"\ftime_created\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vtimeCreated\"w\n" +
	"\rPartySettings\x12\"\n" +
	"\fallowInvites\x18\x01 \x01(\bR\fallowInvites\x12\x1c\n" +
	"\tisPrivate\x18\x02 \x01(\bR\tisPrivate\x12$\n" +
	"\rallowChatting\x18\x03 \x01(\bR\rallowChatting*+\n" +
	"\tPartyRole\x12\n" +
	"\n" +
	"\x06MEMBER\x10\x00\x12\a\n" +
	"\x03MOD\x10\x01\x12\t\n" +
	"\x05OWNER\x10\x02B\xc5\x01\n" +
	"\x15com.mcsports.party.v1B\n" +
	"TypesProtoP\x01Z:github.com/bufbuild/buf-tour/gen/mcsports/party/v1;partyv1\xa2\x02\x03MPX\xaa\x02\x11Mcsports.Party.V1\xca\x02\x11Mcsports\\Party\\V1\xe2\x02\x1dMcsports\\Party\\V1\\GPBMetadata\xea\x02\x13Mcsports::Party::V1b\x06proto3"

var (
	file_mcsports_party_v1_types_proto_rawDescOnce sync.Once
	file_mcsports_party_v1_types_proto_rawDescData []byte
)

func file_mcsports_party_v1_types_proto_rawDescGZIP() []byte {
	file_mcsports_party_v1_types_proto_rawDescOnce.Do(func() {
		file_mcsports_party_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcsports_party_v1_types_proto_rawDesc), len(file_mcsports_party_v1_types_proto_rawDesc)))
	})
	return file_mcsports_party_v1_types_proto_rawDescData
}

var file_mcsports_party_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mcsports_party_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mcsports_party_v1_types_proto_goTypes = []any{
	(PartyRole)(0),                // 0: mcsports.party.v1.PartyRole
	(*Party)(nil),                 // 1: mcsports.party.v1.Party
	(*PartyMember)(nil),           // 2: mcsports.party.v1.PartyMember
	(*PartyInvite)(nil),           // 3: mcsports.party.v1.PartyInvite
	(*PartySettings)(nil),         // 4: mcsports.party.v1.PartySettings
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_mcsports_party_v1_types_proto_depIdxs = []int32{
	4, // 0: mcsports.party.v1.Party.settings:type_name -> mcsports.party.v1.PartySettings
	2, // 1: mcsports.party.v1.Party.members:type_name -> mcsports.party.v1.PartyMember
	3, // 2: mcsports.party.v1.Party.invites:type_name -> mcsports.party.v1.PartyInvite
	0, // 3: mcsports.party.v1.PartyMember.role:type_name -> mcsports.party.v1.PartyRole
	5, // 4: mcsports.party.v1.PartyMember.time_joined:type_name -> google.protobuf.Timestamp
	5, // 5: mcsports.party.v1.PartyInvite.time_created:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_mcsports_party_v1_types_proto_init() }
func file_mcsports_party_v1_types_proto_init() {
	if File_mcsports_party_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcsports_party_v1_types_proto_rawDesc), len(file_mcsports_party_v1_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcsports_party_v1_types_proto_goTypes,
		DependencyIndexes: file_mcsports_party_v1_types_proto_depIdxs,
		EnumInfos:         file_mcsports_party_v1_types_proto_enumTypes,
		MessageInfos:      file_mcsports_party_v1_types_proto_msgTypes,
	}.Build()
	File_mcsports_party_v1_types_proto = out.File
	file_mcsports_party_v1_types_proto_goTypes = nil
	file_mcsports_party_v1_types_proto_depIdxs = nil
}
